export const EDIT_OFFSET = 'EDIT_OFFSET';
export const MAP_HEROES = 'MAP_HEROES';
export const LOADING_HEROES = 'LOADING_HEROES';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const FILTER_FAVOURITES = 'FILTER_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const GET_CURRENT_HERO = 'GET_CURRENT_HERO';
